# Generated by Django 4.1.1 on 2022-09-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
