# Generated by Django 4.0.6 on 2022-09-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
