# Generated by Django 4.0.6 on 2022-09-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Author', max_length=40),
        ),
        migrations.AlterField(
            model_name='author',
            name='info',
            field=models.TextField(),
        ),
    ]
