# Generated by Django 4.0.6 on 2022-09-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0013_book_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cart', models.CharField(max_length=16)),
                ('validity_period_month', models.CharField(max_length=2)),
                ('validity_period_year', models.CharField(max_length=2)),
                ('purchased_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.cart')),
            ],
        ),
    ]
