# Generated by Django 4.0.6 on 2022-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='validity_period_month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='validity_period_year',
        ),
        migrations.AddField(
            model_name='payment',
            name='validity_period',
            field=models.CharField(default='00/00', max_length=5),
        ),
    ]
