# Generated by Django 4.0.6 on 2022-09-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_payment_quantity_alter_payment_purchased_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number_of_cart',
            field=models.IntegerField(),
        ),
    ]
