# Generated by Django 4.0.6 on 2022-09-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_payment_number_of_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='number_of_cart',
            new_name='number_of_card',
        ),
    ]
