# Generated by Django 4.0.6 on 2022-09-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_number_of_cart_payment_number_of_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number_of_card',
            field=models.CharField(max_length=16),
        ),
    ]
