# Generated by Django 4.0.6 on 2022-10-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_payment_number_of_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
